# Generated by Django 4.0.3 on 2022-05-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clenove', '0005_adresaklubovny_alter_oddil_options_alter_oddil_heslo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bobrik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('barva', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Bobrici',
            },
        ),
        migrations.AlterModelOptions(
            name='adresaklubovny',
            options={'verbose_name_plural': 'Adresy Kluboven'},
        ),
        migrations.AlterField(
            model_name='skaut',
            name='oddil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skauti', to='clenove.oddil', verbose_name='Oddil'),
        ),
        migrations.AddField(
            model_name='skaut',
            name='bobrici',
            field=models.ManyToManyField(null=True, related_name='skauti', to='clenove.bobrik'),
        ),
    ]
